# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6de12a73ae6a0f3eb7fb0937db165bb6a4bdf77a94dee359389bcf840595884abba355d048aa9c6767e9b2bcad237936a6f191cd08fbe48756cac0511bf43c9

test:
  secret_key_base: 5e2c9017d96a2bafe04be3b2e7fc455d94d4f10850f52b3df9dc550156c281459b7a2f3abe9561d7a96bdf95fc9b8e2e353c0de96923794dd1c1f11f2afa07cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
